### ISSUE TITLE
Drag Cd*A and Total Drag Force calculations do not seem to be accurate

### ISSUE THREAD

**Issue by Arrowstar** [Ren0k/Project-Atmospheric-Drag#2]
I created a drag profile according to the instructions, but it seems to overestimate the actual drag when I use it with the useProfile.ks script.  I've attached the part database file, the drag profile, and my vessel file.  Any ideas why this might be happening?  I seem to get similar results if I use the Retrograde or Prograde option.

Note that I intentionally have things steered here so that the AoA and sideslip is zero, which is what I created the drag profile with.  

![](https://i.imgur.com/ZU8SZgZ.png)
[dragProfiles.zip](https://github.com/Ren0k/Project-Atmospheric-Drag/files/8558622/dragProfiles.zip)
[PartDatabase.zip](https://github.com/Ren0k/Project-Atmospheric-Drag/files/8558625/PartDatabase.zip)
[Big Launcher 1 Craft File.zip](https://github.com/Ren0k/Project-Atmospheric-Drag/files/8558635/Big.Launcher.1.Craft.File.zip)

**Comment by Ren0k** [comment]
I do not have access to KSP now but I think this might be caused by the custom fairing(s) you have attached to your vessel.
The problem with fairings is that they use a procedural drag cube generation system i.e. their values are not found in the part database cfg file: also see [this section](https://github.com/Ren0k/Project-Atmospheric-Drag#fairings) on fairings.
  
To correct this, you can manually change all the drag cube values per individual part with the drag profile creation tool and manually add the fairing values.
The fairings should come with initial values which are basically just a best guess based on some analysis I did.

**Comment by Arrowstar** [comment]
Thanks for the response!  I don't think it's the fairings.  I removed them and I'm still seeing a large difference in Cd*A and total drag.  Any ideas?

![](https://i.imgur.com/nVRNxdY.png)

**Comment by Ren0k** [comment]
> Thanks for the response!  I don't think it's the fairings.  I removed them and I'm still seeing a large difference in Cd*A and total drag.  Any ideas?
> 
> 
> 
> ![](https://i.imgur.com/nVRNxdY.png)

Did you create a new drag profile without the fairing?
Very likely there are some calculated CdA values that do not match the actual configuration. What I would suggest is to create a new drag profile, but go into the ”special” menu as documented in the readme. Here you can verify the XP/XN..ZN values of all parts and check if there are any mistakes. If there are any mistakes you can manually edit them here. This method also allows you to continue to use the fairing as long as you manually enter the XP..ZN values.

**Comment by Arrowstar** [comment]
> > Thanks for the response!  I don't think it's the fairings.  I removed them and I'm still seeing a large difference in Cd*A and total drag.  Any ideas?
> > ![](https://camo.githubusercontent.com/9c5a609559f7119fbc5655fd7aafafa4bdfd2db492593b5f7ead3edcdb891b48/68747470733a2f2f692e696d6775722e636f6d2f6e56524e7864592e706e67)
> 
> Did you create a new drag profile without the fairing? Very likely there are some calculated CdA values that do not match the actual configuration. What I would suggest is to create a new drag profile, but go into the ”special” menu as documented in the readme. Here you can verify the XP/XN..ZN values of all parts and check if there are any mistakes. If there are any mistakes you can manually edit them here. This method also allows you to continue to use the fairing as long as you manually enter the XP..ZN values.

So I took the fairing away and I'm still seeing overestimated values in the drag force calculation, even after recomputing the profile.  Let me ask this: which orientation sense is appropriate for the way I've got this rocket set up, prograde or retrograde?  I'm using prograde since I assume that means that we're facing "pointy end up", is that correct?

**Comment by Ren0k** [comment]
Correct, in your case you want to use a prograde profile.
What you have to do is go into the 'Manual Edit' menu and verify that the part values used by the drag profile are correct.
Compare the XP/YP etc values in the PAW menu with the drag profile gui (See the screenshot provided).
If they are not correct you can modify them there.
Note, that if you use modded parts the script might not pick them up correctly and you have to manually add them.

![Example](https://user-images.githubusercontent.com/30327252/166114744-2eada511-21f5-4d8a-b2a1-083463935e17.jpg)
o

**Comment by Arrowstar** [comment]
A few questions: Does your code factor in part obscuration (if that's a thing)?  And is that 0.8 global drag modifier factor included in your Cd*A profile that's output?

**Comment by Arrowstar** [comment]
Okay, update!  I think you hit the nail on the head.  I'm using a "test weight" part with custom masses and sizes and that looks like the cause of the issue.  When I compared what was coming out of my profile to KSP, I noticed the difference.

![](https://i.imgur.com/PSA310K.png)

Can you help me understand how I need to update the part config database file in order to get the correct values in there?  I need to do this step because I am creating profiles programmatically and don't have the benefit of the UI.  Here's the entry in the parts database CFG file.

```
PART
{
	url = UtilityWeight/Parts/UtilityWeight_OsmiumTank/UtilityWeight_OsmiumTank/UtilityWeight_OsmiumTank
	DRAG_CUBE
	{
		cube = Default, 1.475,0.7924,0.6966, 1.475,0.7924,0.6966, 1.103,0.6508,0.4545, 1.103,0.6508,0.4545, 1.475,0.7923,0.6966, 1.475,0.7923,0.6966, 0,0,0, 1.244,1.249,1.244
	}
}
```

Thanks!

**Comment by Ren0k** [comment]
The part database contains all default and modded parts in it's default state.
What complicates it is that mods can use different naming conventions for attachment nodes and configuration states.
I think that in your case there is an unrecognized node or config state.

I am not going to start making adjustment for mods as this adds an unlimited line of work for all different mods out there.
What you could do to 'cheat' the system is manually adjusting the part in your copy of the part database file.

**Comment by Arrowstar** [comment]
I think we can close this actually.  I was able to find the definition of the drag cube's format in the part database file and after updating it, my drag profile results are much closer to what KSP is showing.  Thank you for your help with this one! :)
